((nil . ((indent-tabs-mode . nil)))
 (makefile-mode . ((tab-width . 4)))
 (makefile-automake-mode . ((tab-width . 4)))
 (c-mode . ((c-file-style  . "gnu")
            (fill-column . 72)
            (indent-tabs-mode . nil)))
 (c++-mode . ((c-file-style  . "gnu")
            (fill-column . 72)
            (indent-tabs-mode . nil)))
 )
