= The Iris Number System

A textbook series on a constructive number system that contains as
part of its structure a unified field theory for physics.

Included also is an ACL2 “book.” This is a library for the ACL2 proof
assistant that is written in Common Lisp, and which is much friendlier
than most proof assistants are.

The Iris number system replaces continuous real numbers with
indefinitely finely divided discrete ones, corresponding to interval
numbers in computing. Differential calculus is done in the manner of
nonstandard analysis, but constructively: the discrete examination of
detail is done again, but with finer and finer “instruments.” Thus the
mechanical intuition is that of ε-δ—there is no blather about
“infinitesimals”—but the operations performed are the intuitive ones
of nonstandard analysis, requiring no special rules for zero-over-zero
or infinity-over-infinity.

The unified field theory replaces all current theories, including the
gravitational, strong, and weak forces, with just Maxwell’s equations
and the force of electromagnetism. Mass is shown shown to be a
self-induced electromagnetic effect, with inertial and gravitational
mass being the same thing.

All of the universe is filled with an electromagnetic field. There is
no vacuum. There is no “curvature,” either. Space and time are as one
intuitively imagines them. “Space-time” is an artifact of Einstein
implicitly assuming the existence of a luminiferous ether that does
not move.

Forthcoming volumes include Volume VI on applications to fractals and
Volume VII on applications to digital typeface design.
